docker with security enabled
# Build stage

FROM eclipse-temurin:17-jdk-jammy AS build

ENV HOME=/usr/app

RUN mkdir -p $HOME

WORKDIR $HOME

# Install Maven and update certificates

RUN apt-get update && apt-get install -y maven ca-certificates && update-ca-certificates

# Copy pom.xml and source code

COPY pom.xml $HOME

COPY src $HOME/src

# Package the application

RUN mvn -f $HOME/pom.xml clean package -DskipTests -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

# Package stage

FROM eclipse-temurin:17-jre-jammy

COPY --from=build /usr/app/target/*.jar /app/runner.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/runner.jar"]

================


docker run --privileged --rm tonistiigi/binfmt --install all

Dockerfile

#FROM maven:3.8.3-openjdk-17 AS build

FROM eclipse-temurin:17-jdk-jammy AS build

RUN apt-get update && apt-get install -y maven ca-certificates && update-ca-certificates

COPY . /home/app1

WORKDIR /home/app1

RUN mvn -f /home/app1/pom.xml clean package -DskipTests -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

EXPOSE 8080

ENTRYPOINT ["java","-jar","/home/app1/target/app1.jar"]

