services:
  db:
    image: mysql:8.0.12
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MYSQL_DATABASE
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: root
    ports:
      - 3306:3306

